// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Test } from "forge-std/Test.sol";
import { RevenueSplitLib } from "../../../src/shared/libraries/RevenueSplitLib.sol";

/// @title RevenueSplitLibTest
/// @notice The vector pin for `RevenueSplitLib.split`, twinned with the app's mirror of it.
///
///         The app consolidated its split arithmetic into `splitAmount()` in `app/src/lib/revenueSplit.ts`,
///         a mirror of `split` here, and `app/src/lib/revenueSplit.test.ts` asserts that mirror against the
///         SAME ten vectors as `test_vectors_matchesAppMirror` below — same amounts, same expected legs. The
///         expected column was generated by running this library (a throwaway forge test with console.log,
///         not committed), so both files hold the library's own answers and nobody's hand arithmetic. If one
///         side ever needs to change, change the other file's table to match and say why in both commits.
contract RevenueSplitLibTest is Test {
    struct Vector {
        uint256 amount;
        uint256 protocolCut;
        uint256 vaultCut;
        uint256 remainder;
    }

    /// @dev Why these ten: 0 / 1 / 2 — both cuts stay zero below the rounding threshold; 99 / 100 / 101 —
    ///      one wei short of the vault leg reaching 19, the first amount where the protocol leg reaches 1,
    ///      and one past it; 10001 — mid-size with all three legs nonzero and distinct; 1e18 and 1e24 —
    ///      realistic and large; 2**128 — the multiply headroom near the top of what `amount · 19` can take.
    function _vectors() internal pure returns (Vector[10] memory v) {
        v[0] = Vector(0, 0, 0, 0);
        v[1] = Vector(1, 0, 0, 1);
        v[2] = Vector(2, 0, 0, 2);
        v[3] = Vector(99, 0, 18, 81);
        v[4] = Vector(100, 1, 19, 80);
        v[5] = Vector(101, 1, 19, 81);
        v[6] = Vector(10_001, 100, 1_900, 8_001);
        v[7] = Vector(1e18, 10_000_000_000_000_000, 190_000_000_000_000_000, 800_000_000_000_000_000);
        v[8] = Vector(
            1e24, 10_000_000_000_000_000_000_000, 190_000_000_000_000_000_000_000, 800_000_000_000_000_000_000_000
        );
        v[9] = Vector(
            2 ** 128,
            3_402_823_669_209_384_634_633_746_074_317_682_114,
            64_653_649_714_978_308_058_041_175_412_035_960_176,
            272_225_893_536_750_770_770_699_685_945_414_569_166
        );
    }

    /// @dev Twin of `app/src/lib/revenueSplit.test.ts`. Every row is asserted leg by leg, and the three legs
    ///      are checked to conserve the amount so a row that is internally inconsistent cannot pass either.
    function test_vectors_matchesAppMirror() public pure {
        Vector[10] memory v = _vectors();
        for (uint256 i = 0; i < v.length; i++) {
            RevenueSplitLib.Split memory s = RevenueSplitLib.split(v[i].amount);
            assertEq(s.protocolCut, v[i].protocolCut, "protocolCut");
            assertEq(s.vaultCut, v[i].vaultCut, "vaultCut");
            assertEq(s.remainder, v[i].remainder, "remainder");
            assertEq(v[i].protocolCut + v[i].vaultCut + v[i].remainder, v[i].amount, "row conserves the amount");
        }
    }
}
